/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "vending_machine.v:1.1-67.10" *)
module vending_machine(clk, rst_n, nickel, dime, dispense, change);
  (* src = "vending_machine.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "vending_machine.v:3.16-3.21" *)
  input rst_n;
  wire rst_n;
  (* src = "vending_machine.v:4.16-4.22" *)
  input nickel;
  wire nickel;
  (* src = "vending_machine.v:5.16-5.20" *)
  input dime;
  wire dime;
  (* src = "vending_machine.v:6.16-6.24" *)
  output dispense;
  wire dispense;
  (* src = "vending_machine.v:7.22-7.28" *)
  output [1:0] change;
  wire [1:0] change;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* onehot = 32'd1 *)
  wire [4:0] current_state;
  INVX1 _14_ (
    .A(dime),
    .Y(_05_)
  );
  INVX1 _15_ (
    .A(current_state[3]),
    .Y(_06_)
  );
  INVX1 _16_ (
    .A(current_state[0]),
    .Y(_07_)
  );
  INVX1 _17_ (
    .A(current_state[2]),
    .Y(_08_)
  );
  NAND2X1 _18_ (
    .A(nickel),
    .B(_05_),
    .Y(_09_)
  );
  NOR2X1 _19_ (
    .A(nickel),
    .B(dime),
    .Y(_10_)
  );
  AOI22X1 _20_ (
    .A(dime),
    .B(current_state[0]),
    .C(current_state[2]),
    .D(_10_),
    .Y(_11_)
  );
  OAI21X1 _21_ (
    .A(_06_),
    .B(_09_),
    .C(_11_),
    .Y(_02_)
  );
  NAND2X1 _22_ (
    .A(current_state[3]),
    .B(_10_),
    .Y(_12_)
  );
  OAI21X1 _23_ (
    .A(_07_),
    .B(_09_),
    .C(_12_),
    .Y(_03_)
  );
  NOR2X1 _24_ (
    .A(_05_),
    .B(_08_),
    .Y(_00_)
  );
  AND2X1 _25_ (
    .A(current_state[0]),
    .B(_10_),
    .Y(_13_)
  );
  OR2X1 _26_ (
    .A(current_state[1]),
    .B(current_state[4]),
    .Y(dispense)
  );
  OR2X1 _27_ (
    .A(_13_),
    .B(dispense),
    .Y(_01_)
  );
  OAI22X1 _28_ (
    .A(_05_),
    .B(_06_),
    .C(_08_),
    .D(_09_),
    .Y(_04_)
  );
  DFFSR _29_ (
    .CLK(clk),
    .D(_01_),
    .Q(current_state[0]),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _30_ (
    .CLK(clk),
    .D(_00_),
    .Q(current_state[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _31_ (
    .CLK(clk),
    .D(_02_),
    .Q(current_state[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _32_ (
    .CLK(clk),
    .D(_03_),
    .Q(current_state[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _33_ (
    .CLK(clk),
    .D(_04_),
    .Q(current_state[4]),
    .R(rst_n),
    .S(1'h1)
  );
  assign change = { 1'h0, current_state[1] };
endmodule
